# database.py

# Do not edit!  This is machine generated by running "python row.py".

from table import *


Items = Tables['Items']

Products = Tables['Products']

Inventory = Tables['Inventory']

Orders = Tables['Orders']

Attendance = Tables['Attendance']

Categories = Tables['Categories']

Reconcile = Tables['Reconcile']

