# database.py

# Do not edit!  This is machine generated by running "python row.py".

from table import *


Items = Tables['Items']

Products = Tables['Products']

Inventory = Tables['Inventory']

Orders = Tables['Orders']

Months = Tables['Months']

Globals = Tables['Globals']

Accounts = Tables['Accounts']

Starts = Tables['Starts']

Reconcile = Tables['Reconcile']

